---
# tasks file for ucsdlib.java
# Download and install Oracle Java
# Based on https://github.com/hudecof/ansible_java

- name: Is Java Installed Already?
  stat:
    path: '{{ java_install_dir ~ "/" ~ java_unpacked_directory ~ "/bin/java" }}'
  register: bin_java
  tags:
    - java
    - setup

- block:
  - name: "Create Install Directory"
    file:
      path: '{{ java_install_dir }}'
      state: directory
    tags:
      - java
      - setup

# TODO: Secure Directory

  - block:
    - name: "Copy cached tgz file, if available"
      copy:
       src: '{{ java_download_uri | basename }}'
       dest: '{{ java_download_dir }}/oracle_java.tar.gz'
      tags:
        - java
        - setup

    rescue:

    - name: "Download Upstream tgz file"
      get_url:
        url: '{{ java_download_uri }}'
        dest: '{{ java_download_dir }}/oracle_java.tar.gz'
        force: '{{ java_force_download | default (false) }}'
        headers:
          'Cookie: oraclelicense=accept-securebackup-cookie'
        checksum: '{{ java_available[java_version]["checksum_" ~ java_architecture] | default ("") }}'
      environment:
        '{{ java_webproxy | default ({}) }}'
      tags:
        - java
        - setup

  # end block

  - name: "unpack java"
    unarchive:
      src: '{{ java_download_dir }}/oracle_java.tar.gz'
      dest: '{{ java_install_dir }}'
      copy: no
    tags:
      - java
      - setup

  - name: remove install file
    file:
      path: '{{ java_download_dir }}/oracle_java.tar.gz'
      state: absent
    tags:
      - java
      - setup

  when: not bin_java.stat.exists

- name: Set Default Java
  file:
    path: '{{ java_install_dir }}/java'
    src: '{{ java_install_dir ~ "/" ~ java_unpacked_directory }}'
    state: link
  when: java_set_default
  ignore_errors: '{{ ansible_check_mode }}'
  tags:
    - java
    - setup

- name: Set Compatibility Symlinks
  file:
    path: /usr/local/bin/{{ item }}
    src: '{{ java_install_dir }}/java/bin/{{ item }}'
    state: link
  with_items:
    - java
  when: java_set_compatibility_symlink | default (false)
  tags:
    - java
    - setup
